/**
 * Interactive deployment environment setup script
 * Helps configure all necessary environment variables for deployment
 */

import * as readline from 'readline';
import * as fs from 'fs';
import * as path from 'path';

interface DeploymentConfig {
  PRIVATE_KEY: string;
  BASE_RPC_URL?: string;
  BASE_SEPOLIA_RPC_URL?: string;
  BASESCAN_API_KEY?: string;
  ALCHEMY_BASE_URL?: string;
  INFURA_BASE_URL?: string;
  BLOXROUTE_API_KEY?: string;
  EXECUTION_PRIVATE_KEY?: string;
  WALLET_ADDRESS?: string;
}

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

function question(query: string): Promise<string> {
  return new Promise(resolve => {
    rl.question(query, resolve);
  });
}

async function setupDeploymentEnvironment(): Promise<DeploymentConfig> {
  console.log('=== Base MEV Platform - Deployment Environment Setup ===\n');

  const config: DeploymentConfig = {
    PRIVATE_KEY: '',
  };

  // Required: Private key for deployment
  console.log('1. Deployment Wallet Configuration');
  console.log('   This wallet will deploy the FlashExecutor contract');
  const privateKey = await question('   Enter deployment private key (0x...): ');
  config.PRIVATE_KEY = privateKey.trim();

  if (!config.PRIVATE_KEY.startsWith('0x')) {
    config.PRIVATE_KEY = '0x' + config.PRIVATE_KEY;
  }

  // Execution wallet (can be same or different)
  console.log('\n2. Execution Wallet Configuration');
  console.log('   This wallet will execute MEV strategies (can be same as deployment)');
  const useSameWallet = await question('   Use same wallet for execution? (y/n): ');

  if (useSameWallet.toLowerCase() === 'y') {
    config.EXECUTION_PRIVATE_KEY = config.PRIVATE_KEY;
  } else {
    const execKey = await question('   Enter execution private key (0x...): ');
    config.EXECUTION_PRIVATE_KEY = execKey.trim();
    if (!config.EXECUTION_PRIVATE_KEY.startsWith('0x')) {
      config.EXECUTION_PRIVATE_KEY = '0x' + config.EXECUTION_PRIVATE_KEY;
    }
  }

  // RPC URLs
  console.log('\n3. RPC Provider Configuration');
  const rpcChoice = await question(
    '   Choose RPC provider:\n   1) Public Base RPC (free, rate-limited)\n   2) Alchemy (recommended)\n   3) Infura\n   4) Custom\n   Enter choice (1-4): '
  );

  switch (rpcChoice.trim()) {
    case '1':
      config.BASE_RPC_URL = 'https://mainnet.base.org';
      config.BASE_SEPOLIA_RPC_URL = 'https://sepolia.base.org';
      break;
    case '2':
      const alchemyKey = await question('   Enter Alchemy API key: ');
      config.BASE_RPC_URL = `https://base-mainnet.g.alchemy.com/v2/${alchemyKey.trim()}`;
      config.BASE_SEPOLIA_RPC_URL = `https://base-sepolia.g.alchemy.com/v2/${alchemyKey.trim()}`;
      config.ALCHEMY_BASE_URL = config.BASE_RPC_URL;
      break;
    case '3':
      const infuraKey = await question('   Enter Infura project ID: ');
      config.BASE_RPC_URL = `https://base-mainnet.infura.io/v3/${infuraKey.trim()}`;
      config.BASE_SEPOLIA_RPC_URL = `https://base-sepolia.infura.io/v3/${infuraKey.trim()}`;
      config.INFURA_BASE_URL = config.BASE_RPC_URL;
      break;
    case '4':
      config.BASE_RPC_URL = await question('   Enter Base mainnet RPC URL: ');
      config.BASE_SEPOLIA_RPC_URL = await question('   Enter Base Sepolia RPC URL: ');
      break;
    default:
      console.log('   Invalid choice, using public RPC');
      config.BASE_RPC_URL = 'https://mainnet.base.org';
      config.BASE_SEPOLIA_RPC_URL = 'https://sepolia.base.org';
  }

  // BaseScan API key (optional but recommended)
  console.log('\n4. BaseScan API Key (optional, for contract verification)');
  const useBasescan = await question('   Configure BaseScan API key? (y/n): ');
  if (useBasescan.toLowerCase() === 'y') {
    config.BASESCAN_API_KEY = await question('   Enter BaseScan API key: ');
  }

  // bloXroute API key (optional but important for MEV)
  console.log('\n5. bloXroute Configuration (optional, for MEV protection)');
  const useBloxroute = await question('   Configure bloXroute API key? (y/n): ');
  if (useBloxroute.toLowerCase() === 'y') {
    config.BLOXROUTE_API_KEY = await question('   Enter bloXroute API key: ');
  }

  return config;
}

function generateEnvFile(config: DeploymentConfig): string {
  const lines: string[] = [
    '# Base MEV Platform - Environment Configuration',
    '# Generated by setup-deployment-env.ts',
    '',
    '# Deployment Configuration',
    `PRIVATE_KEY=${config.PRIVATE_KEY}`,
    `EXECUTION_PRIVATE_KEY=${config.EXECUTION_PRIVATE_KEY || config.PRIVATE_KEY}`,
    '',
    '# Network Configuration',
    `BASE_RPC_URL=${config.BASE_RPC_URL || 'https://mainnet.base.org'}`,
    `BASE_SEPOLIA_RPC_URL=${config.BASE_SEPOLIA_RPC_URL || 'https://sepolia.base.org'}`,
    'BASE_WS_URL=wss://mainnet.base.org',
    'BASE_CHAIN_ID=8453',
    '',
  ];

  if (config.ALCHEMY_BASE_URL) {
    lines.push(`ALCHEMY_BASE_URL=${config.ALCHEMY_BASE_URL}`);
  }

  if (config.INFURA_BASE_URL) {
    lines.push(`INFURA_BASE_URL=${config.INFURA_BASE_URL}`);
  }

  if (config.BASESCAN_API_KEY) {
    lines.push('');
    lines.push('# BaseScan Configuration');
    lines.push(`BASESCAN_API_KEY=${config.BASESCAN_API_KEY}`);
  }

  if (config.BLOXROUTE_API_KEY) {
    lines.push('');
    lines.push('# Private Relay Configuration');
    lines.push(`BLOXROUTE_API_KEY=${config.BLOXROUTE_API_KEY}`);
  }

  lines.push('');
  lines.push('# Contract Addresses (will be set after deployment)');
  lines.push('FLASH_EXECUTOR_ADDRESS=');
  lines.push('');
  lines.push('# Strategy Configuration');
  lines.push('MIN_PROFIT_USD=15');
  lines.push('MAX_SLIPPAGE_BPS=100');
  lines.push('MAX_GAS_PRICE_GWEI=0.1');
  lines.push('');
  lines.push('# Health Check Configuration');
  lines.push('HEALTH_CHECK_PORT=3002');
  lines.push('');

  return lines.join('\n');
}

async function main() {
  try {
    const config = await setupDeploymentEnvironment();

    console.log('\n=== Configuration Summary ===');
    console.log('Deployment Wallet: Configured');
    console.log('Execution Wallet:', config.EXECUTION_PRIVATE_KEY ? 'Configured' : 'Not set');
    console.log('RPC Provider:', config.BASE_RPC_URL);
    console.log('BaseScan API:', config.BASESCAN_API_KEY ? 'Configured' : 'Not set');
    console.log('bloXroute API:', config.BLOXROUTE_API_KEY ? 'Configured' : 'Not set');

    const envContent = generateEnvFile(config);

    console.log('\n=== Next Steps ===');
    const save = await question('Save configuration to .env file? (y/n): ');

    if (save.toLowerCase() === 'y') {
      const envPath = path.join(process.cwd(), '.env');

      // Backup existing .env if it exists
      if (fs.existsSync(envPath)) {
        const backupPath = path.join(process.cwd(), `.env.backup.${Date.now()}`);
        fs.copyFileSync(envPath, backupPath);
        console.log(`Existing .env backed up to: ${backupPath}`);
      }

      fs.writeFileSync(envPath, envContent);
      console.log('Configuration saved to .env');

      console.log('\n=== Ready for Deployment ===');
      console.log('1. Test on Sepolia first: npm run deploy:testnet');
      console.log('2. Deploy to mainnet: npm run deploy:mainnet');
      console.log('3. Test connectivity: npm run test:relay');
    } else {
      console.log('\nConfiguration not saved. Here is the content:\n');
      console.log(envContent);
    }

    rl.close();
  } catch (error) {
    console.error('Error during setup:', error);
    rl.close();
    process.exit(1);
  }
}

main();
